### ISSUE TITLE
Broken page layout in French

### ISSUE THREAD

**Issue by pyrog** [okfn/opendataday#287] opened 2021-01-27 08:31 UTC
Hi,

The layout is broken in french:
<img width="50%" alt="French" src="https://user-images.githubusercontent.com/2158081/105964264-3bc95f80-6082-11eb-8934-dfb37ef703c7.png">

<img width="50%" alt="English" src="https://user-images.githubusercontent.com/2158081/105964271-3ec45000-6082-11eb-8438-62702de17a33.png">

**Comment by pyrog** [comment] 2021-01-27 08:37
This is Open Data Day **2020** in french 😉

**Comment by lwinfree** [comment] 2021-01-28 18:24
good catch @pyrog! I think your edits to the translation will fix this problem, since I think it is being caused by the length of the text not fitting into the space on the site. I will leave this issue open until those edits are merged so we can check & make sure it is fixed.

**Closed** 2021-01-28 21:55 UTC
